// LINKS ROUTER
const HOME_PAGE = '/';
const LOGIN_PAGE = '/login';
const REGISTER_PAGE = '/register';
const CONTACT_PAGE = '/contact';
const NEWS_PAGE = '/news';
const PROFILE_PAGE = '/user-profile';
const ADMIN_PAGE = '/admin';

// REDUCERS
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const USER_PROFILE = 'USER_PROFILE'; 
const UPDATE_PROFILE = 'UPDATE_PROFILE'; 
const REGISTER_SUCESS='REGISTER_SUCESS';
const REGISTER_FAILURE='REGISTER_FAILURE';


// LOCALSTORAGE KEY CONSTANTS
const LOCAL_STORAGE_TOKEN_KEY = '@token';
const LOCAL_STORAGE_CREDENTIALS_KEY = '@credentials';
const LOCAL_STORAGE_PROFILE_KEY = '@profile';
const CLEAR_STORE = 'CLEAR_STORE';

export {HOME_PAGE, LOGIN_PAGE, REGISTER_PAGE, CONTACT_PAGE, NEWS_PAGE, PROFILE_PAGE, ADMIN_PAGE};
export {LOGIN_SUCCESS, LOGIN_FAILURE, USER_PROFILE, UPDATE_PROFILE ,REGISTER_SUCESS, REGISTER_FAILURE};
export {LOCAL_STORAGE_TOKEN_KEY, LOCAL_STORAGE_CREDENTIALS_KEY, CLEAR_STORE, LOCAL_STORAGE_PROFILE_KEY};



